import fetch from 'node-fetch';

let handler = async (m, { text, command, usedPrefix, conn }) => {
  if (!text)
    throw `*🖼️ This command generates images from text prompts*\n\n*📌 Example usage:*\n◉ ${usedPrefix + command} Beautiful anime girl\n◉ ${usedPrefix + command} Elon Musk in pink outfit`

  try {
    await m.react('⏳');

    const query = encodeURIComponent(text);
    const url = `https://flux.gtech-apiz.workers.dev/?apikey=APIKEY&text=${query}`;

    const res = await fetch(url);

    if (!res.ok) throw `❎ Failed to generate image: ${res.statusText}`;
    
    const buffer = await res.buffer();
    const caption = `*Generated by Flux*\n📌 *Prompt:* ${text}\n\n🔗 https://whatsapp.com/channel/0029VagJIAr3bbVBCpEkAM07`;
    
    await conn.sendFile(m.chat, buffer, 'flux.jpg', caption, m);

  } catch (e) {
      m.react('❎');
    console.error(e);
    throw `❎ Failed to generate image. Try again later.\n\n${e.message || e}`;
  }
};

handler.help = ['flux'];
handler.tags = ['ai'];
handler.command = ['flux', 'lexica'];
handler.limit = true
export default handler;
