import fetch from 'node-fetch'
import uploadImage from '../lib/uploadImage.js'

let handler = async (m, { conn, text, usedPrefix, command }) => {
  if (!text)
    throw `*🖼️ This command generates images from text prompts*\n\n*📌 Example usage:*\n◉ ${usedPrefix + command} Beautiful anime girl\n◉ ${usedPrefix + command} Elon Musk in pink outfit`

  try {
    m.react('⏳')

    const endpoint = `https://stable.gtech-apiz.workers.dev/?apikey=APIKEY&prompt=${encodeURIComponent(text)}`

    const response = await fetch(endpoint)

    if (response.ok) {
      const imageBuffer = await response.buffer()
      const imgurl = await uploadImage(imageBuffer)

      await conn.sendFile(m.chat, imgurl, 'image.jpg', '*Generated by Stable*', m)
    } else {
      throw '*❌ Image generation failed*'
    }
  } catch (e) {
    console.error(e)
    throw '*⚠️ Oops! Something went wrong while generating image. Please try again later.*'
  }
}

handler.help = ['stable']
handler.tags = ['ai']
handler.command = ['dalle', 'stable']
handler.limit = true
export default handler
