import fetch from 'node-fetch'

let handler = async (m, { conn, text, usedPrefix, command }) => {
  if (!text)
    throw `*🖼️ This command generates images from text prompts*\n\n*📌 Example usage:*\n◉ ${usedPrefix + command} Beautiful anime girl\n◉ ${usedPrefix + command} Elon Musk in pink outfit`

  try {
    m.react('⏳')
    const query = encodeURIComponent(text);

    const url = `https://stable.gtech-apiz.workers.dev/?apikey=APIKEY&prompt=${encodeURIComponent(query)}`

    const res = await fetch(url)

if (!res.ok) throw `❎ Failed to generate image: ${res.statusText}`;
    
    const buffer = await res.buffer();
    const caption = `*Generated by Stable*\n📌 *Prompt:* ${text}\n\n🔗 https://whatsapp.com/channel/0029VagJIAr3bbVBCpEkAM07`;
    
    await conn.sendFile(m.chat, buffer, 'stable.jpg', caption, m);

  } catch (e) {
      m.react('❎');
    console.error(e);
    throw `❎ Failed to generate image. Try again later.\n\n${e.message || e}`;
  }
};

handler.help = ['stable']
handler.tags = ['ai']
handler.command = ['dalle', 'stable']
handler.limit = true
export default handler
